APP_NAME = "OI Scanner Pro"
VERSION = "1.0.0"

LANGUAGE = "en"

DATABASE_NAME = "oi_scanner.db"

DEFAULT_EXCHANGE = "Bybit"
SUPPORTED_EXCHANGES = ("Bybit", "Binance", "OKX")

DEFAULT_THEME = "Dark"

TELEGRAM_ENABLED = False

LICENSE_ENABLED = True

DEFAULT_ALERT_OI_THRESHOLD = 0.20
DEFAULT_ALERT_VOLUME_THRESHOLD = 0.20
DEFAULT_ALERT_FUNDING_THRESHOLD = 0.0001
DEFAULT_ALERT_SCORE_THRESHOLD = 6
ALERT_COOLDOWN_SECONDS = 900

REALTIME_ENABLED = True
REALTIME_RECONNECT_SECONDS = 5
REALTIME_SYMBOL_LIMIT = 100
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
LICENSE_VALIDATION_URL = ""
UPDATE_MANIFEST_URL = ""
